name: flutter_jab_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.6
  lottie: ^1.3.0
  cached_network_image: ^3.2.0

  # networking
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  pretty_dio_logger: ^1.1.1

  freezed: ^2.2.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1

  # logging
  logger: ^1.1.0

  # localization
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true